# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_instance_id', models.CharField(max_length=100)),
                ('bk_biz_id', models.CharField(max_length=100)),
                ('job_instance_name', models.CharField(max_length=500)),
                ('jobStatus', models.CharField(max_length=50)),
                ('isDispose', models.CharField(max_length=50)),
                ('createdDate', models.CharField(max_length=200)),
                ('updatedDate', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'JobWork',
            },
        ),
    ]
